config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :users, only: [:new, :create, :show] do
    resources :favorites, only: [:create, :delete]
  end

  namespace :admin do
	 resources :homepage, only: [:index]
   resources :plants, only: [:new, :create, :destroy, :edit, :update]
   resources :green_houses
	end

  resources :plants, except: [:new, :create, :destroy, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :plant
end

app/models/green_house.rb
class GreenHouse < ApplicationRecord
  has_many :plants
  validates_presence_of :name, :location

  def plant_count
    plants.count
  end
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :green_house
  has_many :favorites
  has_many :users, through: :favorites
  
  validates_presence_of :name, :variety, :sell_quantity, :stock_plants, :zone, :shipping
  scope :ordered_plants, -> { order(name: :asc) }

end

app/models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness: true, presence: true
  validates_presence_of :password, require: true
  has_many :favorites
  has_many :plants, through: :favorites
  has_secure_password
  enum role: %w(default admin)
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: '/public/404' unless current_admin?
  end
end

app/controllers/admin/green_houses_controller.rb
class Admin::GreenHousesController < Admin::BaseController

  def index
    @green_houses = GreenHouse.all
  end

  def new
    @green_house = GreenHouse.new
  end

  def create
    @green_house = GreenHouse.create(green_house_params)
    redirect_to admin_green_house_path(@green_house)
  end

  def show
    @green_house = GreenHouse.find(params[:id])
  end

  def edit
    @green_house = GreenHouse.find(params[:id])
  end

  def update
    @green_house = GreenHouse.find(params[:id])
    @green_house.update(green_house_params)
    if @green_house.save
      flash[:success] = "#{@green_house.name} updated!"
      redirect_to admin_green_house_path(@green_house)
    else
      render :edit
    end
  end

  def destroy
    @green_house = GreenHouse.find(params[:id])
    if @green_house.destroy
      flash[:success] = "#{@green_house.name} deleted."
    end
    redirect_to admin_green_houses_path
  end

  private

  def green_house_params
    params.require(:green_house).permit(:name, :location)
  end
end

app/controllers/admin/homepage_controller.rb
class Admin::HomepageController < Admin::BaseController
  
  def index
  end
end

app/controllers/admin/plants_controller.rb
class Admin::PlantsController < Admin::BaseController

  def index
    @plants = Plant.all
  end

  def new
    @plant = Plant.new
    @green_houses = GreenHouse.all
  end

  def create
    @plant = Plant.create(plant_params)
    @green_house = GreenHouse.find(plant_params[:green_house_id])
    redirect_to plant_path(@plant)
  end

  def destroy
    @plant = Plant.find(params[:id])
    if @plant.destroy
      flash[:success] = "#{@plant.name} deleted."
    end
    redirect_to plants_path
  end

  def edit
    @plant = Plant.find(params[:id])
    @green_houses = GreenHouse.all
  end

  def update
    @plant = Plant.find(params[:id])
    @plant.update(plant_params)
    if @plant.save
      flash[:success] = "#{@plant.name} updated!"
      redirect_to plant_path(@plant)
    else
      render :edit
    end
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :variety, :sell_quantity,
                                  :stock_plants, :zone, :shipping, :green_house_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :current_admin?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

  def authorize
    redirect_to login_path, alert: 'You must be logged in to access this page.' if current_user.nil?
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
   @favorite = Favorite.create(favorite_params)
   redirect_to user_path(params[:user_id])
  end

 def destroy
   @favorite = Favorite.find(params[:id])
   @favorite.destroy
   redirect_to user_path(params[:user_id])
 end

 private
   def favorite_params
     params.require(:favorite).permit(:user_id, :plant_id)
   end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def index
    @plants = Plant.ordered_plants
  end

  def show
    @plant = Plant.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user), notice: 'Successfully logged in!'
    else
      flash.now.alert = "Incorrect email or password, try again."
      render :new
    end
  end

  def destroy
   session.delete(:user_id)
   redirect_to login_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    @user.username.downcase!

    if @user.save
      flash[:notice] = "Account created successfully!"
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash.now.alert = "Couldn't create account. Please make sure you are using a valid email and password and try again."
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @favorites = Favorite.where(user_id: params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def index
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/green_houses/edit.html.erb
<h1>Edit <%= @green_house.name %></h1>

<%= form_for [:admin, @green_house] do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.submit "Submit changes" %>
<% end %>

app/views/admin/green_houses/index.html.erb
<p class="h1 text-center" style="color: #654C4F">All Greenhouses</p>

<ul class="list-group"><ul>
  <% @green_houses.each do |gh| %>
  <li class="list-group-item"><strong><%= link_to gh.name, admin_green_house_path(gh) %></strong></li>
  <li class="list-group-item">Location: <%= gh.location %></li>
  <li class="list-group-item">Current number of plants: <%= gh.plant_count %></li>
    <% end %>
</ul>

app/views/admin/green_houses/new.html.erb
<h1>Add Greenhouse</h1>

<%= form_for [:admin, @green_house] do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.submit "Create greenhouse" %>
<% end %>

app/views/admin/green_houses/show.html.erb
<p class="h1 text-center" style="color: #654C4F"><%= @green_house.name %></p>
<p class="h1 text-center" style="color: #654C4F">Location: <%= @green_house.location %></p>


<main class="container">
  <div class="card-columns item-columns">
    <% @green_house.plants.ordered_plants.each do |plant| %>
      <div class="card">
        <img class="card-img-top" src= "<%= plant.image %>", size:"300x300">
        <div class="card-body">
          <h6 class="card-title h6"><%= link_to plant.name, plant_path(plant) %></h6>
        </div>
      </div>
    <% end %>
  </div>
</main>

app/views/admin/homepage/index.html.erb
<h1> Administrator Homepage </h1>

app/views/admin/plants/edit.html.erb
<h1>Edit<%= @plant.name %></h1>

<%= form_for [:admin, @plant] do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :GreenHouse %>
  <%= f.collection_select(:green_house_id, @green_houses, :id, :name) %>

  <%= f.label :variety %>
  <%= f.text_field :variety %>

  <%= f.label :sell_quantity %>
  <%= f.text_field :sell_quantity %>

  <%= f.label :stock_plants %>
  <%= f.text_field :stock_plants %>

  <%= f.label :zone %>
  <%= f.text_field :zone %>

  <%= f.label :shipping %>
  <%= f.text_field :shipping %>

  <%= f.label :image %>
  <%= f.text_field :image %>

<%= f.submit "Submit changes" %>
<% end %>

app/views/admin/plants/index.html.erb
<h1>List of all plants</h1>

<% @plants.each do |plant| %>
  <%= link_to plant.name, plant_path(plant) %>
  <%= link_to 'Edit Plant', edit_admin_plant_path(plant) %>
  <%= link_to 'Delete Plant', admin_plant_path(plant), method: :delete %>
<% end %>

  <!-- <%= link_to 'Edit plant', edit_admin_plant_path(plant) %>
  <%= link_to 'Delete plant', admin_plant_path(plant), method: :delete %> -->
 <% end %>

 <% @plants.each do |plant| %>


 <main class="container">
   <div class="card-columns item-columns">
     <% @plants.each do |plant| %>
       <div class="card">
         <img class="card-img-top" src="/<%= plant.image %>">
         <div class="card-body">
           <p class="card-text"><%= link_to 'Edit Plant', edit_admin_plant_path(plant) %></p>
           <p class="card-text"><%= link_to 'Delete Plant', admin_plant_path(plant), method: :delete %></p>
         </div>
       </div>
     <% end %>
   </div>
 </main>

 <p class="h1 text-center" style="color: #654C4F">All Available Plants</p>

  <main class="container">
    <div class="card-columns item-columns">
      <% @plants.each do |plant| %>
        <div class="card">
          <img class="card-img-top" src= "<%= plant.image %>, size:"300x300">
          <div class="card-body">
            <h6 class="card-title h6"><%= link_to plant.name, plant_path(plant) %></h6>
            <p class="card-text"><%= link_to 'Edit Plant', edit_admin_plant_path(plant) %></p>
            <p class="card-text"><%= link_to 'Delete Plant', admin_plant_path(plant), method: :delete %></p>
          </div>
        </div>
      <% end %>
    </div>
  </main>

app/views/admin/plants/new.html.erb
<h1> Add a new plant </h1>

<%= form_for [:admin, @plant] do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :GreenHouse %>
  <%= f.collection_select(:green_house_id, @green_houses, :id, :name) %>

  <%= f.label :variety %>
  <%= f.text_field :variety %>

  <%= f.label :sell_quantity %>
  <%= f.text_field :sell_quantity %>

  <%= f.label :stock_plants %>
  <%= f.text_field :stock_plants %>

  <%= f.label :zone %>
  <%= f.text_field :zone %>

  <%= f.label :shipping %>
  <%= f.text_field :shipping %>

  <%= f.label :image %>
  <%= f.text_field :image %>

<%= f.submit "Submit" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Greenhouse</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>

    <nav class="navbar navbar-light" style="background-color: #D8D0C1;">
      <a class="navbar-brand" href="#">ColdHardyCactus</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <% if current_admin? %>
        <%= link_to 'Home', root_path %> | <%= link_to 'View all plants', plants_path %> | <%= link_to 'Add plant', new_admin_plant_path %> | <%= link_to 'All greenhouses', admin_green_houses_path %> | <%= link_to 'Add greenhouse', new_admin_green_house_path %> | <%= link_to 'Log Out', logout_path, method: :delete %>
      <% elsif current_user %>
        <%= "Logged in as #{current_user.username}" %> | <%= link_to 'Home', root_path %> | <%= link_to 'View all plants', plants_path %> | <%= link_to 'Log Out', logout_path, method: :delete %>
      <% else %>
        <%= link_to 'Home', root_path %> | <%= link_to 'View all plants', plants_path %> | <%= link_to 'Log In', login_path %> or <%= link_to 'Sign Up', new_user_path %>
      <% end %>

      <% if notice %>
        <%= notice %>
  	  <% end %>

  	  <% if alert %>
        <%= alert %>
  	  <% end %>
    </nav>
  <div class="background_image">
    <body>

    <%= yield %>

    </body>
  </div>
</html>

app/views/plants/index.html.erb
 <p class="h1 text-center" style="color: #654C4F">All Available Plants</p>

  <main class="container">
    <div class="card-columns item-columns">
      <% @plants.each do |plant| %>
        <div class="card">
          <img class="card-img-top" src= "<%= plant.image %>", size:"300x300">
          <div class="card-body">
            <h6 class="card-title h6"><%= link_to plant.name, plant_path(plant) %></h6>
            <p class="card-text"><%= link_to 'Edit Plant', edit_admin_plant_path(plant) %></p>
            <p class="card-text"><%= link_to 'Delete Plant', admin_plant_path(plant), method: :delete %></p>
            <p class="card-text"><% if current_user %>
              <%= form_for current_user.favorites.new, url: user_favorites_path(current_user) do |f| %>
              <%= f.hidden_field :user_id, value: current_user.id %>
              <%= f.hidden_field :plant_id, value: plant.id %>
              <%= f.submit 'Add plant to favorites' %>
                  <% end %>
                <% end %>
            </p>
          </div>
        </div>
      <% end %>
    </div>
  </main>

app/views/plants/show.html.erb
<p class="h1 text-center" style="color: #654C4F"><%= @plant.name %></p>

<main class="container">
  <div class="card-columns item-columns">
      <div class="card">
        <img class="card-img-top" src= "<%= @plant.image %>", size:"300x300">
        <div class="card-body">
          <h6 class="card-title h6">Variety: <%= @plant.variety %></h6>
          <h6 class="card-title h6">Quantity: <%= @plant.sell_quantity %></h6>
          <h6 class="card-title h6">Stock plants: <%= @plant.stock_plants %></h6>
          <h6 class="card-title h6"><%= @plant.zone %></h6>
          <h6 class="card-title h6">Shipping requirements: <%= @plant.shipping %></h6>
          <p class="card-text"><%= link_to 'Edit Plant', edit_admin_plant_path(@plant) %></p>
          <p class="card-text"><%= link_to 'Delete Plant', admin_plant_path(@plant), method: :delete %></p>
        </div>
      </div>
  </div>
</main>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>

  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome, <%= current_user.username %>!</h1>
<% @favorites.each do |favorite| %>
  <%= favorite.plant.name %>
  <%= image_tag(favorite.plant.image, size: "300x300") %>
<% end %>